// Generated by CoffeeScript 1.8.0
var Player,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Player = (function() {
  function Player() {
    this.doKeyDown = __bind(this.doKeyDown, this);
    window.addEventListener("keydown", this.doKeyDown, true);
  }

  Player.prototype.move = function(grid, snake, snack) {};

  Player.prototype.doKeyDown = function(e) {
    if (game.running === false) {
      game.startGame();
    }
    if (e.keyCode === 37) {
      game.makeMove(-1, 0);
    }
    if (e.keyCode === 38) {
      game.makeMove(0, -1);
    }
    if (e.keyCode === 39) {
      game.makeMove(1, 0);
    }
    if (e.keyCode === 40) {
      return game.makeMove(0, 1);
    }
  };

  return Player;

})();

window.Player = Player;
